expname: CL1_1

defaults:
  - data: default
  - model: default
  - logging: default
  - optim: default

hydra:
  run:
    dir: ${workpath}/outputs/${now:%Y-%m-%d}/${expname}

core:
  version: 1.0
  tags:
    - ${now:%Y-%m-%d}

workpath: /code/CL