_target_: pxrdgen.model.diffusion.CSPDiffusion
time_dim: 256
latent_dim: 256
cost_coord: 1.
cost_lattice: 1.
timesteps: 1000

encoder_xrd_fix: None
ckpt_path: ${workpath}/pre_ckpt/
encoder_xrd_ckpt: CL.ckpt
encoder_xrd:
  _target_: pxrdgen.model.encoder_xrd.xrd_encoder_T
  hidden_size: 128
  num_layers: 4
  num_heads: 4
  dropout: 0.1
  latent_size: ${model.latent_dim}

decoder: 
  _target_: pxrdgen.model.cspnet.CSPNet
  hidden_dim: 512
  latent_dim: ${model.latent_dim}
  max_atoms: 100
  num_layers: 6
  act_fn: silu
  dis_emb: sin
  num_freqs: 128
  ln: true
  ip: true

beta_scheduler: 
  _target_: pxrdgen.model.diff_utils.BetaScheduler
  timesteps: ${model.timesteps}
  scheduler_mode: cosine

sigma_scheduler: 
  _target_: pxrdgen.model.diff_utils.SigmaScheduler
  timesteps: ${model.timesteps}
  sigma_begin: 0.005
  sigma_end: 0.5


